### PR TITLE
procps should be restarted, as it may be running

### PR DESCRIPTION
**Pull request by hh**
I ran into errors running this on hosts where it was already running.

### CODE REVIEW

**Comment by irvingpop** [comment]
This seems weird.   Chef should no-op on `action :start` if the service is already running, right?    Could it be selecting the wrong service provider on your platform?

**Comment by stevendanna** [comment]
The load_current_resource function of the upstart provider is....interesting: https://github.com/chef/chef/blob/master/lib/chef/provider/service/upstart.rb#L99-L155

**Comment by stevendanna** [comment]
I think this is good to go.  Sorry this took so long to look at @hh.  

I originally thought the :restart might be a problem on some versions of upstart.  But it looks like we already cover that case in the provider: https://github.com/chef/chef/blob/master/lib/chef/provider/service/upstart.rb#L185-L197

**Comment by stevendanna** [comment]
@irvingpop OK.  So right before merging I took another look at this based on your comment. I think that the existing call to start should be fine from a chef recipe perspective but that we actually do want a restart.

You are correct that if the upstart provider is being chosen, the :start action is a no-op:

https://github.com/chef/chef/blob/master/lib/chef/provider/service/upstart.rb#L157-L169

So, unless you are getting the wrong provider or we are detecting the wrong status for this service. The cookbook should run to completion(another item in play here, is that we very recently upgraded the version of chef-client that we use in the package):

```
vagrant@vagrant:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.10
Release:        14.10
Codename:       utopic
vagrant@vagrant:~$ sudo ls /etc/sysctl.d/90-postgresql.conf
ls: cannot access /etc/sysctl.d/90-postgresql.conf: No such file or directory
vagrant@vagrant:~$ sudo /sbin/status procps
procps start/running
vagrant@vagrant:~$ sudo chef-server-ctl reconfigure
[...SNIP...]
vagrant@vagrant:~$ echo $?
0
```

However, the goal of that part of the recipe is to make sure that our new sysctl's get into place.  `procps` as a service is actually just a run-once script:

```
script
    cat /etc/sysctl.d/*.conf /etc/sysctl.conf | sysctl -e -p -
end script
```

Thus, if we don't restart it, the new settings don't get read in which might cause other errors.  (It is potentially these errors that hippiehacker was running into.)

Thoughts?  I'll merge this today if the above makes sense to you.

**Comment by stevendanna** [comment]
cc @chef/lob as well

**Comment by irvingpop** [comment]
Ah, great explanation @stevendanna !   :+1: :shipit:

**Comment by stevendanna** [comment]
Merged here: 5c4a5d6fde61d5ebf2f6cb8e844e8260c9fe0420

**Pull request closed without merging**
