### PR TITLE
Use the strip-version sofwware from Delivery to reduce package size

### PR DESCRIPTION
**Pull request by stevendanna**

### CODE REVIEW

**Comment by marcparadise** [comment]
:+1:

**Comment by stevendanna** [comment]
The concern here is whether losing debugging symbols is actually worth it.  For instance it would prevent us from using a systemtap enable build (cc @manderson26).

**Comment by stevendanna** [comment]
Note, however, that we do exclude erlang from the items we strip.  I don't know whether that is enough to preserve the debugging abilities we want.

This saves us about 50MB in the final 10.04 artifiacts.

**Comment by stevendanna** [comment]
Moved https://github.com/chef/chef-server/pull/169

**Pull request closed without merging**
