### PR TITLE
Move to oc_erchef 1.8.2

### PR DESCRIPTION
**Pull request by stevendanna**
Changelog-Entry: Improved performance fo the cookbook_verions endpoint
for large installations

### CODE REVIEW

**Comment by mmzyk** [comment]
@stevendanna of instead of fo in the Changelog-Entry. Also, is it ChangeLog or Changelog? Does it matter?

**Comment by stevendanna** [comment]
@mmzyk Thanks, typos on both fronts.  It is ChangeLog-Entry.  Perhaps I it should be case insensitive?

**Comment by mmzyk** [comment]
@stevendanna case insensitivity is probably good, that way it's one less thing to think about.

changelog-entry is a bit easy to type and requires less thinking. ;)

**Comment by irvingpop** [comment]
:heart: thanks for pulling this in to Chef Server so quickly

**Pull request merged**
