### PR TITLE
eldap only likes lowercase for attribs

### PR DESCRIPTION
**Pull request by sean-horn**
zendesk 2877 + https://github.com/chef/opscode-omnibus/issues/694

### CODE REVIEW

**Comment by marcparadise** [comment]
Have you retested the scenario after @stevendanna 's recent changes this week? I think this will no longer be necessary.

**Comment by stevendanna** [comment]
Should be fixed by: https://github.com/chef/oc_erchef/blob/master/apps/oc_chef_wm/src/oc_chef_wm_authn_ldap.erl#L181-L183

**Comment by stevendanna** [comment]
@sean-horn In the interest of closing the loop, I'm going to close this PR.  Please leave the branch as we can reopen it and use this fix if we find the changes in oc_erchef don't do the job.

**Comment by sean-horn** [comment]
Closed https://github.com/chef/opscode-omnibus/issues/694. The oc_erchef fix LGTM. Leaving the branch.

**Pull request closed without merging**
