### PR TITLE
Pull in 0.5.1 of enterprise-chef-common

### PR DESCRIPTION
**Pull request by manderson26**
This passes CI (http://wilson.ci.chef.co/job/chef-server-12-trigger-ad_hoc/308) and should be a straightforward merge.

@chef/server-team @marcparadise @sdelano

### CODE REVIEW

**Comment by manderson26** [comment]
Passes CI

**Comment by tylercloke** [comment]
LGTM, any changes being pulled in we should know / be worried about / go in the changelog?

**Comment by manderson26** [comment]
Thanks; I'd forgotten the changelog. This adds preliminary systemd support. I'll add a changelog entry.

**Comment by irvingpop** [comment]
:+1: once changelog is in

**Comment by kramvan1** [comment]
Thx for the systemd efforts here, much appreciated.

**Pull request merged**
