### PR TITLE
[OC-11648] EC11: Mitigate Undefined Cluster Behavior with Full Log or Data Disk

### PR DESCRIPTION
**Pull request by sean-horn**

### CODE REVIEW

**Comment by stevendanna** [comment]
@sean-horn Wow. Sorry it took so long for us to get to this (I imagine you've heard this a lot by now, huh).

We looked at this today and wanted to get a bit more detail on what the behavior will be with this patch in place.  What does going into a fault state mean in terms of what happens to the cluster?  Will we be failing over to a machine with a disk that is also full because it has been replicating the same data?

**Comment by sean-horn** [comment]
Yeah, which will lead to a safety shutdown of the entire system, thus allowing the operators to cleanup and start back up.

**Comment by stevendanna** [comment]
@sean-horn Thanks.  We like this change but think it is really important to make the percentage disk space configurable.

**Comment by stevendanna** [comment]
@sean-horn I rebased this against master and moved the PR to the new Chef Server repository:

https://github.com/chef/chef-server/pull/171

Please let me know if you spot any problems.

**Pull request closed without merging**
