### PR TITLE
Move chef-mover to master

### PR DESCRIPTION
**Pull request by stevendanna**
Moving chef-mover to master will help the eventual code merge as we are currently a few commits behind.  This is also required for RHEL7 builds.

### CODE REVIEW

**Comment by stevendanna** [comment]
Do not merge until chef/chef-mover#76 is merged and the current upgrade issue with chef-mover faster is fixed.  I will comment on this PR once that is done.

**Comment by stevendanna** [comment]
cc @chef/lob

**Comment by stevendanna** [comment]
My branch of chef-mover is now working with upgrades again.  This still needs to be merged after that branch is merged.

**Comment by tylercloke** [comment]
:+1:

**Pull request merged**
