### PR TITLE
Zendesk 2938 Fix yum install errors

### PR DESCRIPTION
**Pull request by sean-horn**

### CODE REVIEW

**Comment by stevendanna** [comment]
@sean-horn Thanks for the PR.  It would be great if you could update your commit message to describe the problem.  As I understand it the problem is that yum's transaction history will report an error if any message was written by the postinst script.

**Comment by ymattw** [comment]
@sean-horn Could you take a minute update the commit log?  Thanks.

**Comment by sdelano** [comment]
+1 on @stevendanna's request. Not even everyone internal at CHEF can get to Zendesk to look at that ticket, so it would be extremely useful to have a summary of the issue in the commit message.

Thanks!

**Comment by ryancragun** [comment]
@sdelano @stevendanna @sean-horn @ymattw With Sean's permission I've updated the commit log message, rebased, and updated the CHANGELOG.

**Comment by stevendanna** [comment]
Merged here: https://github.com/chef/opscode-omnibus/commit/37c699875a3f5eb9cc6690615347c7f2b8311cee

Thanks!

**Pull request closed without merging**
