### PR TITLE
Ssd/remote download fixes

### PR DESCRIPTION
**Pull request by stevendanna**

### CODE REVIEW

**Comment by jonlives** [comment]
Awesome! I'll try and give this a shot at some point soon

**Comment by sdelano** [comment]
@jonlives - did you ever get a chance to test this out?

**Comment by jonlives** [comment]
Not yet - we had a bunch of issues to work through with the data dump / import process first...hoping to test this out relatively quickly after chefconf.

**Comment by sdelano** [comment]
Thanks for the update!

**Comment by stevendanna** [comment]
Moved this here: https://github.com/chef/chef-server/pull/170

**Pull request closed without merging**
