### PR TITLE
Allow users to turn ACL restricted searching on or off

### PR DESCRIPTION
**Pull request by thommay**
Dependent on chef/oc_erchef#107

### CODE REVIEW

**Comment by marcparadise** [comment]
:+1:

**Comment by marcparadise** [comment]
Additional: Please add a CHANGELOG.md entry and RELEASE_NOTES.md  section to indicate the new setting availability.

**Comment by thommay** [comment]
@marcparadise Done. Is there any facility to set things differently for new installs, rather than upgrades? Seems like we might want to enable this for new stuff but leave it off for old...

**Comment by thommay** [comment]
This has now been merged.

**Pull request closed without merging**
